- name: Remove legacy docker web services
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - wedding99
  tags:
    - cleanup

- name: Remove legacy folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/wedding99
    - /var/nginx-proxy/html/wedding99
  tags:
    - cleanup

- name: Create directories for hpshare server
  tags:
    - hpshare
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/hpshare
    - /var/nginx-proxy/html/hpshare

- name: Copy config file for hpshare server
  tags: hpshare
  copy:
    src: hpshare/config.py
    dest: /var/hpshare/config.py

- import_tasks: roles/docker/tasks/virtual-host-nginx-extra.yml
  tags: hpshare
  vars:
    host: "{{ hpshare.domain }}"
    static_url_path: "/~static/"
    static_dir: "hpshare"

- name: Configure docker hpshare
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: hpshare
    image: blahgeek/hpurl:0.4.1
    volumes:
      - /var/hpshare:/data
      - /var/nginx-proxy/html/hpshare:/static
    env:
      DJANGO_SECRET_KEY: "{{ hpshare.django_secret_key }}"
      DJANGO_ALLOWED_HOST: "{{ hpshare.domain }}"
      DJANGO_STATIC_ROOT: "/static"
      ADMIN_USER: "{{ hpshare.admin_user }}"
      ADMIN_EMAIL: "{{ hpshare.admin_email }}"
      ADMIN_PASSWD: "{{ hpshare.admin_password }}"
      VIRTUAL_PORT: "8000"
      VIRTUAL_PROTO: "uwsgi"
      VIRTUAL_HOST: "{{ hpshare.domain }}"
      LETSENCRYPT_HOST: "{{ hpshare.domain }}"
    expose: 8000
  tags: hpshare

- name: Configure docker blog website
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: blog
    image: blahgeek/blog:20240812-2307
    env:
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "blog.blahgeek.com,z1k.dev"
      LETSENCRYPT_HOST: "blog.blahgeek.com,z1k.dev"
    expose: 80
  tags: blog

