- name: Create directories for hpshare server
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/hpshare
    - /var/searxng

- name: Copy config file for hpshare server
  copy:
    src: hpshare/config.py
    dest: /var/hpshare/config.py

- name: Configure docker hpshare
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: hpshare
    image: blahgeek/hpurl:0.3.3
    volumes:
      - /var/hpshare:/data
    env:
      DJANGO_SECRET_KEY: "{{ hpshare.django_secret_key }}"
      DJANGO_ALLOWED_HOST: "{{ hpshare.domain }}"
      ADMIN_USER: "{{ hpshare.admin_user }}"
      ADMIN_EMAIL: "{{ hpshare.admin_email }}"
      ADMIN_PASSWD: "{{ hpshare.admin_password }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "{{ hpshare.domain }}"
      LETSENCRYPT_HOST: "{{ hpshare.domain }}"
    expose: 80

- name: Configure docker blog website
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: blog
    image: blahgeek/blog:20220603-2225
    env:
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "blog.blahgeek.com,z1k.dev"
      LETSENCRYPT_HOST: "blog.blahgeek.com,z1k.dev"
    expose: 80

- name: Copy config file for searxng
  copy:
    src: searxng/settings.yml
    dest: /var/searxng/settings.yml
  notify: Restart docker searxng

- name: Configure docker searxng
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: searxng
    image: searxng/searxng:2022.08.07-04e34270
    volumes:
      - /var/searxng/:/etc/searxng/
    env:
      VIRTUAL_PORT: "8080"
      VIRTUAL_HOST: "search.z1k.dev"
      LETSENCRYPT_HOST: "search.z1k.dev"
      INSTANCE_NAME: "Search.z1k.dev"
      BASE_URL: "https://search.z1k.dev/"
    expose: 8080

- name: Configure uwsgi config for docker searxng (after docker start)
  lineinfile:
    path: /var/searxng/uwsgi.ini
    regexp: "^workers =.*"
    line: "workers = 1"
  notify: Restart docker searxng
