- assert:
    that: ansible_os_family == 'Debian'

- name: Install nat64 packages
  package:
    name:
      - tayga
    state: present
  tags:
    - nat64

- name: Render tayga config for debian
  template:
    src: tayga.debian_conf.j2
    dest: /etc/default/tayga
  notify:
    - Reload tayga service
  tags:
    - nat64

- name: Render tayga config
  template:
    src: tayga.conf.j2
    dest: /etc/tayga.conf
  notify:
    - Reload tayga service
  tags:
    - nat64

- name: Configure iptables filter for nat64
  iptables_raw:
    ipversion: 6
    name: nat64_filter
    table: filter
    rules: |
      -A INPUT ! -s {{ yikai_net.home_prefix }} -d {{ ipv6_prefix | ansible.utils.ipsubnet(64, 0x6464) | ansible.utils.ipsubnet(96, 0) }} -j DROP
  tags:
    - nat64
