all:
  children:
    wall:
      hosts:
        wall.blahgeek.com:
          ansible_host: 192.243.120.32
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
