all:
  children:
    wall:
      hosts:
        wall-test0.blahgeek.com:
          ansible_host: 45.33.47.12
        wall.blahgeek.com:
          ansible_host: 192.243.120.32
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
