all:
  children:
    wall:
      hosts:
        wall.blahgeek.com:
          ansible_host: 67.230.173.40
    eastwatch:
      hosts:
        eastwatch.blahgeek.com:
          ansible_host: 149.28.71.244
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
    fleabottom:
      hosts:
        fleabottom.blahgeek.com:
          ansible_host: 8.130.14.239
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
