all:
  children:
    wall:
      hosts:
        wall.blahgeek.com:
          ansible_host: 80.251.211.31
    eastwatch:
      hosts:
        eastwatch.blahgeek.com:
          ansible_host: 149.28.71.244
    # mhome:
    #   hosts:
    #     mhome.blahgeek.com:
    #       ansible_host: 192.168.0.1
    highgarden:
      hosts:
        highgarden.blahgeek.com:
          ansible_host: 192.168.0.1
    fleabottom:
      hosts:
        fleabottom.blahgeek.com:
          ansible_host: 47.92.242.60
    north:
      hosts:
        north.blahgeek.com:
          ansible_host: 188.245.57.116
    north_bgp:
      hosts:
        north-bgp.blahgeek.com:
          ansible_host: 2a0c:9a40:2510:1001::10e4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
