all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
    # ansible hostvars only works when connected to host
    # since we only need static vars, define them explicitly
    my_hostvars: &my_hostvars
      wall.blahgeek.com:
        ansible_host: 104.255.70.190
        ipv6_prefix: 2a0e:b107:178d::/48
        vpn_subnet_id: 42
      eastwatch.blahgeek.com:
        ansible_host: 149.28.71.244
        ipv6_prefix: 2a06:a005:08d2::/48
        vpn_subnet_id: 43

      dragonstone.blahgeek.com:
        ansible_host: 45.76.195.106
        ipv6_prefix: 2a0e:b107:178c::/48
      harrenhal.blahgeek.com:
        ansible_host: 5.188.38.163
        ipv6_prefix: 2a0e:b107:178e::/48
        vpn_subnet_id: 44

      highgarden.blahgeek.com:
        ansible_host: 192.168.0.1
        ipv6_prefix: 2a0e:aa07:e035::/48

      fleabottom.blahgeek.com:
        ansible_host: 47.92.242.60
      mudgate.blahgeek.com:
        ansible_host: 39.98.54.132
        # NOTE: this is for internal usage only. maybe use private range or a smaller subnet?
        ipv6_prefix: 2a0e:b107:178f::/48

  hosts: *my_hostvars
