all:
  children:
    wall_master:
      hosts:
        wall.blahgeek.com:
          ansible_host: 67.230.174.235
    wall_slave:
      hosts:
        eastwatch.blahgeek.com:
          ansible_host: 194.147.71.75
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
