all:
  children:
    wall:
      hosts:
        wall.blahgeek.com:
          ansible_host: 67.230.174.235
    # ironisland:
    #   hosts:
    #     ironisland.blahgeek.com:
    #       ansible_host: 2.59.214.253
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
