all:
  children:
    wall:
      hosts:
        wall.blahgeek.com:
          ansible_host: 89.208.251.190
    eastwatch:
      hosts:
        eastwatch.blahgeek.com:
          ansible_host: 149.28.71.244
    mhome:
      hosts:
        mhome.blahgeek.com:
          ansible_host: 192.168.0.1
    fleabottom:
      hosts:
        fleabottom.blahgeek.com:
          ansible_host: 8.130.14.239
    kingsroad:
      hosts:
        kingsroad.blahgeek.com:
          ansible_host: 198.13.40.151
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
