[project]
name = "blahinit"
version = "0.1.0"
description = "This file is only for recording ansible versions so that `uv run' works."
requires-python = ">=3.12"
dependencies = [
    "ansible<11",
    "ansible-core>=2.17.12",
    "netaddr>=1.3.0",
]
