- hosts: wall_master
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: sync-server
    - role: web-server
    - role: bgp-server

- hosts: wall_slave
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server

- hosts: mhome
  roles:
    - role: wall-vpn-client
