- hosts: wall
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: sync-server
    - role: web-server
    - role: bgp-server

- hosts: eastwatch
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server
    - role: sync-server

- hosts: kingsroad
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server

- hosts: mhome
  roles:
    - role: wall-vpn-client

- hosts: fleabottom
  roles:
    - role: common-server
    - role: beian-web-server
