- hosts: wall
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: sync-server
    - role: web-server
    - role: bgp-server

- hosts: eastwatch
  roles:
    - role: common-server
    - role: bgp-server

- hosts: mhome
  roles:
    - role: wall-vpn-client
