- hosts: wall.blahgeek.com
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: nat64-server
    - role: bgp-server
    - role: proxy-server
    - role: web-server

- hosts: eastwatch.blahgeek.com
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: nat64-server
    - role: bgp-server
    - role: sync-server
    - role: proxy-server

- hosts: whitetree.blahgeek.com
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: nat64-server
    - role: bgp-server
    - role: docker

- hosts: highgarden.blahgeek.com
  roles:
    - role: wall-vpn-client
    - role: wireguard

- hosts: mudgate.blahgeek.com
  roles:
    - role: common-server
    - role: common-wall
    - role: nat64-server
    - role: wireguard
