- hosts: wall
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server
    - role: proxy-server
    - role: web-server

- hosts: eastwatch
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server
    - role: sync-server
    - role: proxy-server

- hosts: mhome
  roles:
    - role: wall-vpn-client

- hosts: fleabottom
  roles:
    - role: common-server
    - role: beian-web-server
    - role: wedding-server
    - role: tailscale-derp
    - role: tailscale-node
    - role: tailproxy

- hosts: north
  roles:
    - role: common-server
    - role: bgp-server
    - role: wall-vpn-server
    - role: proxy-server
