- hosts: wall.blahgeek.com
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server
    - role: proxy-server
    - role: web-server

- hosts: eastwatch.blahgeek.com
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: bgp-server
    - role: sync-server
    - role: proxy-server

- hosts: highgarden.blahgeek.com
  roles:
    - role: wall-vpn-client
    - role: wireguard

- hosts: fleabottom.blahgeek.com
  roles:
    - role: common-server
    - role: beian-web-server
    - role: wedding-server
    - role: tailscale-derp
    - role: tailscale-node
    - role: tailproxy

- hosts: north.blahgeek.com
  roles:
    - role: common-server
    - role: bgp-server
    - role: wall-vpn-server
    - role: proxy-server

- hosts: mudgate.blahgeek.com
  roles:
    - role: common-server
    - role: common-wall
    - role: wireguard
