- hosts: wall
  roles:
    - role: common-server
    - role: wall-vpn-server
    - role: sync-server
    - role: web-server

# - hosts: ironisland
#   roles:
#     - role: common-server
#     - role: wall-vpn-server
#     - role: sync-server

- hosts: mhome
  roles:
    - role: wall-vpn-client
