- name: Copy beian web content
  copy:
    src: web/
    dest: /var/beian-web/

- name: Configure beian-web server docker
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: beian-web
    image: nginx:1.23.0
    volumes:
      - /var/beian-web:/usr/share/nginx/html:ro
    env:
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "blahgeek.com,www.blahgeek.com"
      LETSENCRYPT_HOST: "blahgeek.com,www.blahgeek.com"
    expose: 80
