- assert:
    that: ansible_os_family == 'Debian'

- name: Configure network related sysctl for bgp server
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "net.ipv6.ip_nonlocal_bind", "value": "1"}
  tags:
    - bgp

- name: Configure tunnelbroker
  when: tunnelbroker is defined
  template:
    src: tunnelbroker.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}"
  with_dict: "{{ tunnelbroker }}"
  notify:
    - Delete old tunnelbroker interfaces
    - Reload tunnelbroker interfaces
  tags:
    - bgp

- name: Remove legacy ipv6 SNPT config
  iptables_raw:
    ipversion: 6
    name: ipv6_snpt
    table: mangle
    state: absent
  tags:
    - bgp

- name: Install BIRD
  package:
    name:
      - bird
    state: present
  tags:
    - bgp

- name: Disable BIRDv4
  systemd:
    name: bird
    enabled: false
    state: stopped
  tags:
    - bgp

- name: Install BIRDv6 config
  template:
    src: bird6.conf.j2
    dest: /etc/bird/bird6.conf
  notify: Reload BIRDv6 service
  tags:
    - bgp

- name: Enable BIRDv6
  systemd:
    name: bird6
    enabled: true
    state: started
  tags:
    - bgp
