wall_servers:
  - name: wall
    host: wall.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3000
      route_v4:
        table: 1
        fwmark: '0x1/0xf'
      route_v6:
        default: true
  - name: eastwatch
    host: eastwatch.blahgeek.com
    openvpn:
      phantun:
        id: 2
        client_listen_port: 3101
      route_v4:
        table: 3
        fwmark: '0x3/0xf'
      route_v6:
        default: false

absent_wall_servers:
  - ironisland
