# route_v4 and route_v6 have different mechanisms... see mhome's iptable rules.
# for route_v4, the default route is the china net;
# for route_v6, the default route is the yikai net.
wall_servers:
  - name: eastwatch
    host: eastwatch.blahgeek.com
    openvpn:
      phantun:
        id: 2
        client_listen_port: 3101
      route_v4:
        table: 3
        fwmark: '0x3/0xf'
      route_v6:
        table: 3
        fwmark: '0x3/0xf'
        uids:
          - transmission
  - name: kingsroad
    host: kingsroad.blahgeek.com
    openvpn:
      forward:
        # address: b-jp.vxtrans.com
        # port: 33925
        address: sh-jp.iplc-zf.ink-iplc.com
        port: 10124
      route_v4:
        table: 1
        fwmark: '0x1/0xf'
      route_v6:
        default: true

absent_wall_servers:
  - ironisland
  - wall
