# route_v4 and route_v6 have different mechanisms... see mhome's iptable rules.
# for route_v4, the default route is the china net;
# for route_v6, the default route is the yikai net.
wall_servers:
  - name: wall
    host: wall.blahgeek.com
    openvpn:
      # udp2raw:
      #   client_listen_port: 3000
      phantun:
        id: 1
        client_listen_port: 3100
      route_v4:
        table: 1
        fwmark: '0x1/0xf'
      route_v6:
        default: true
  - name: eastwatch
    host: eastwatch.blahgeek.com
    openvpn:
      # forward:
      #   address: di4gdf-sh-us-fdf66.inkiwike.com
      #   port: 23333
      phantun:
        id: 2
        client_listen_port: 3101
      route_v4:
        table: 3
        fwmark: '0x3/0xf'
      route_v6:
        table: 3
        fwmark: '0x3/0xf'

absent_wall_servers:
  - ironisland
  - kingsroad
