- name: Download and extract dnsproxy
  ansible.builtin.unarchive:
    src: https://github.com/AdguardTeam/dnsproxy/releases/download/v0.75.1/dnsproxy-linux-amd64-v0.75.1.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy dnsproxy binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-amd64/dnsproxy
    dest: /usr/local/bin/dnsproxy
    mode: '0755'
    remote_src: yes

- name: Install dnsproxy services
  copy:
    dest: /etc/systemd/system/dnsproxy@.service
    src: ../common-wall/files/systemd/dnsproxy@.service

- name: Create /etc/dnsproxy folder
  file:
    path: "/etc/dnsproxy"
    state: directory
    mode: 0755
