- name: Install packages for vpn
  package:
    name:
      - openvpn
    state: present
  tags:
    - wall-client

- name: Copy openvpn keys
  copy:
    src: ../common-wall/files/openvpn/static.key
    dest: /etc/openvpn/static.key
  tags:
    - wall-client
