- name: Configure network related sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", "value": "1"}
    - { name: "net.ipv4.tcp_window_scaling", "value": "1"}
    - { name: "net.ipv4.tcp_syncookies", "value": "1"}
    - { name: "net.core.rmem_max", "value": "16777216"}
    - { name: "net.core.wmem_max", "value": "16777216"}
    - { name: "net.ipv4.tcp_rmem", "value": "4096 87380 16777216"}
    - { name: "net.ipv4.tcp_wmem", "value": "4096 65536 16777216"}
    - { name: "net.ipv4.conf.default.rp_filter", "value": "2"}
    - { name: "net.ipv4.conf.all.rp_filter", "value": "2"}
    - { name: "net.ipv6.conf.all.forwarding", "value": "1"}
    - { name: "net.core.default_qdisc", "value": "fq"}
    - { name: "net.ipv4.tcp_congestion_control", "value": "bbr"}

- name: Install kissvpn
  unarchive:
    src: https://github.com/blahgeek/kissvpn/releases/download/v0.1.5/kissvpn_v0.1.5_x86_64-unknown-linux-musl.zip
    dest: /usr/local/bin
    include:
      - kissvpn
    mode: 0755
    remote_src: yes
  tags:
    - vpn
    - wall-client

- name: Install kissvpn services
  copy:
    dest: "/etc/systemd/system/{{ item }}.service"
    src: "systemd/{{ item }}.service"
  with_items:
    - kissvpn-server
    - kissvpn-client@
  tags:
    - vpn
    - wall-client

- name: Create /etc/kissvpn folder
  file:
    path: "/etc/kissvpn"
    state: directory
    mode: 0755
  tags:
    - vpn
    - wall-client
