- name: Configure network related sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", "value": "1"}
    - { name: "net.ipv4.tcp_window_scaling", "value": "1"}
    - { name: "net.ipv4.tcp_syncookies", "value": "1"}
    - { name: "net.core.rmem_max", "value": "16777216"}
    - { name: "net.core.wmem_max", "value": "16777216"}
    - { name: "net.ipv4.tcp_rmem", "value": "4096 87380 16777216"}
    - { name: "net.ipv4.tcp_wmem", "value": "4096 65536 16777216"}
    - { name: "net.ipv4.conf.default.rp_filter", "value": "2"}
    - { name: "net.ipv4.conf.all.rp_filter", "value": "2"}
    - { name: "net.ipv6.conf.all.forwarding", "value": "1"}
    - { name: "net.core.default_qdisc", "value": "fq"}
    - { name: "net.ipv4.tcp_congestion_control", "value": "bbr"}

# for some reason, `hostvars[item.host].ipv6_prefix` does not work directly in client's template
- name: Set facts from hostvars so that client can reference them in template
  set_fact:
    ipv6_prefix: "{{ ipv6_prefix | default('') }}"
  tags: always
