- name: Configure network related sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", "value": "1"}
    - { name: "net.ipv4.tcp_window_scaling", "value": "1"}
    - { name: "net.ipv4.tcp_syncookies", "value": "1"}
    - { name: "net.core.rmem_max", "value": "16777216"}
    - { name: "net.core.wmem_max", "value": "16777216"}
    - { name: "net.ipv4.tcp_rmem", "value": "4096 87380 16777216"}
    - { name: "net.ipv4.tcp_wmem", "value": "4096 65536 16777216"}
    - { name: "net.ipv4.conf.default.rp_filter", "value": "2"}
    - { name: "net.ipv4.conf.all.rp_filter", "value": "2"}
    - { name: "net.ipv6.conf.all.forwarding", "value": "1"}
    - { name: "net.core.default_qdisc", "value": "fq"}
    - { name: "net.ipv4.tcp_congestion_control", "value": "bbr"}

- name: Install phantun
  unarchive:
    src: https://github.com/dndx/phantun/releases/download/v0.5.0/phantun_x86_64-unknown-linux-gnu.zip
    dest: /usr/local/bin/
    include:
      - phantun_server
      - phantun_client
    mode: 0755
    remote_src: yes

- name: Install phantun services
  copy:
    dest: "/etc/systemd/system/phantun-{{ item }}@.service"
    src: "systemd/phantun-{{ item }}@.service"
  with_items:
    - server
    - client

- name: Create /etc/phantun folder
  file:
    path: "/etc/phantun/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - server
    - client
