version: '2'
name: composes  # backward compatibility

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        # NOTE: in home-net, but not in :d0ce:: range,
        # because :d0ce:: range is public (allow incoming connections), while others are not.
        # so containers with only "default" network will have a usable ipv6 address for outgoing connections (essential since nat64 is used for non-cn domains),
        # but is still not reachable from outside.
        - subnet: 2a0e:aa07:e035:d0cf::/80
  external:
    enable_ipv6: true
    ipam:
      config:
        # NOTE: the default docker network (outside of this compose project) uses ...:0001::/80 (in /etc/docker/daemon.json)
        - subnet: 2a0e:aa07:e035:d0ce::/80

# NOTE:
# 1. The default network of this compose project is "default" (actually named "composes_default"),
#    which is ipv4 only and essentially internal (without forwarding)

# 2. For public services,
#    in ipv6 network, only serve in yikai-net (no nat or port expose required, use container's ip directly);
#       (except tailproxy, which is special)
#    in ipv4 network, serve from mudgate (via port forwarding)

volumes:
  nextcloud-app:
  nextcloud-db:
  html:
  certs:
  acme:

services:
  nginx-proxy:
    restart: unless-stopped
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
      - ENABLE_IPV6=true
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-files/nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
      external:
        ipv6_address: 2a0e:aa07:e035:d0ce::6666

  acme-companion:
    restart: unless-stopped
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=letsencrypt@blahgeek.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - external

  whoami:
    restart: unless-stopped
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.highgarden.blahgeek.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.highgarden.blahgeek.com

  beian-web:
    restart: unless-stopped
    image: blahgeek/beian-web:20251208
    container_name: beian-web
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=blahgeek.com,www.blahgeek.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=blahgeek.com,www.blahgeek.com

  # Serve https proxy (forward to 192.168.0.1 tinyproxy)
  # It can be accessed in two ways:
  # - tailproxy.highgarden-dyn.
  #   the domain resolves differently for CN and others
  #   * CN: china-unicom ipv6
  #   * GLOBAL: same as web.highgarden., yikai-net ipv6 and mudgate ipv4
  #     (so that letsencrypt can successfully access it, because china-unicom ipv6 cannot serve http)
  # - tailproxy.highgarden-v4.
  #   * only mudgate ipv4
  #
  # But anyway, they are forwarded to the ipv6 address of this docker
  #
  tailproxy:
    restart: unless-stopped
    image: blahgeek/tailproxy:0.5
    container_name: tailproxy
    environment:
      - STUNNEL_CERT_DIR=/certs/tailproxy.highgarden-dyn.blahgeek.com/
      # yes.. the below line works. interesting
      - STUNNEL_LOCAL_PORT=2a0e:aa07:e035:d0ce::9607:8888
      - STUNNEL_REMOTE=192.168.0.1:8888
      # virtual_port is actually useless
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=tailproxy.highgarden-dyn.blahgeek.com,tailproxy.highgarden-v4.blahgeek.com
      - LETSENCRYPT_HOST=tailproxy.highgarden-dyn.blahgeek.com,tailproxy.highgarden-v4.blahgeek.com
    volumes:
      - certs:/certs:ro
    # all forwarded to ipv6, no need for port mapping
    expose:
      - "8888"
    networks:
      default:
      external:
        ipv6_address: 2a0e:aa07:e035:d0ce::9607

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    image: nextcloud:30-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    expose:
      - "80"
    volumes:
      - nextcloud-app:/var/www/html
      - /data/NextcloudData:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - APACHE_DISABLE_REWRITE_IP=1
      # https://github.com/nextcloud/documentation/pull/11295
      - APACHE_BODY_LIMIT=8589934592
      - TRUSTED_PROXIES=172.16.0.0/12
      - VIRTUAL_HOST=nextcloud.highgarden.blahgeek.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nextcloud.highgarden.blahgeek.com

  nextcloud-cron:
    # same image & volume & mysql environment as above
    image: nextcloud:30-apache
    container_name: nextcloud-cron
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud-app:/var/www/html
      - /data/NextcloudData:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    entrypoint: /cron.sh

  # use onlyoffice now.
  # # the builtin one in nextcloud-app does not contain proper fonts
  # nextcloud-office:
  #   image: collabora/code
  #   container_name: nextcloud-office
  #   restart: unless-stopped
  #   expose:
  #     - "9980"
  #   environment:
  #     - server_name=nextcloud-office.highgarden.blahgeek.com
  #     - extra_params=--o:ssl.enable=false --o:ssl.termination=true
  #     - aliasgroup1=https://nextcloud.highgarden.blahgeek.com:443
  #     - VIRTUAL_HOST=nextcloud-office.highgarden.blahgeek.com
  #     - VIRTUAL_PORT=9980
  #     - LETSENCRYPT_HOST=nextcloud-office.highgarden.blahgeek.com

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - VIRTUAL_HOST=onlyoffice.highgarden.blahgeek.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=onlyoffice.highgarden.blahgeek.com

  smokeping:
    restart: unless-stopped
    image: linuxserver/smokeping@sha256:d118c7100ded8ccfce7a2c66e0c1f00ce138b3b67eb42ef62e05bc4c57edfff1
    container_name: smokeping
    expose:
      - "80"
    volumes:
      - /var/docker-files/smokeping/data:/data
      - /var/docker-files/smokeping/config:/config
    environment:
      - VIRTUAL_HOST=smokeping.highgarden.blahgeek.com
      - LETSENCRYPT_HOST=smokeping.highgarden.blahgeek.com
      - VIRTUAL_PORT=80

  inkstand-render-server:
    container_name: inkstand-render-server
    image: blahgeek/inkstand-render-server:0.2
    restart: unless-stopped
    environment:
      - API_KEY=${INKSTAND_RENDER_SERVER_APIKEY}
      - VIRTUAL_HOST=inkstand-render-server.highgarden.blahgeek.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=inkstand-render-server.highgarden.blahgeek.com
    expose:
      - "3000"
