name: "composes"
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2a0e:aa07:e035:d0ce:8000::/80"
  external:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2a0e:aa07:e035:d0ce::/80"
services:
  acme-companion:
    container_name: "nginx-proxy-acme"
    environment:
      - "DEFAULT_EMAIL=letsencrypt@blahgeek.com"
    image: "nginxproxy/acme-companion"
    networks:
      default: {}
      external:
        gw_priority: 10
    restart: "unless-stopped"
    volumes:
      - "certs:/etc/nginx/certs:rw"
      - "acme:/etc/acme.sh"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
  beian-web:
    container_name: "beian-web"
    environment:
      - "VIRTUAL_HOST=blahgeek.com,www.blahgeek.com"
      - "VIRTUAL_PORT=8000"
      - "LETSENCRYPT_HOST=blahgeek.com,www.blahgeek.com"
    expose:
      - "8000"
    image: "blahgeek/beian-web:20251208"
    restart: "unless-stopped"
  grafana:
    container_name: "grafana"
    environment:
      - "VIRTUAL_HOST=grafana.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=3000"
      - "LETSENCRYPT_HOST=grafana.highgarden.blahgeek.com"
      - "GF_DEFAULT_INSTANCE_NAME=highgarden"
    expose:
      - "3000"
    image: "grafana/grafana-oss"
    restart: "unless-stopped"
    volumes:
      - "grafana-data:/var/lib/grafana"
  inkstand-render-server:
    container_name: "inkstand-render-server"
    environment:
      - "VIRTUAL_HOST=inkstand-render-server.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=3000"
      - "LETSENCRYPT_HOST=inkstand-render-server.highgarden.blahgeek.com"
      - "API_KEY=${INKSTAND_RENDER_SERVER_APIKEY}"
    expose:
      - "3000"
    image: "blahgeek/inkstand-render-server:0.2"
    restart: "unless-stopped"
  nextcloud-app:
    container_name: "nextcloud-app"
    depends_on:
      - "nextcloud-db"
    environment:
      - "VIRTUAL_HOST=nextcloud.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=nextcloud.highgarden.blahgeek.com"
      - "MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=nextcloud-db"
      - "APACHE_DISABLE_REWRITE_IP=1"
      - "APACHE_BODY_LIMIT=8589934592"
      - "TRUSTED_PROXIES=172.16.0.0/12"
    expose:
      - "80"
    image: "nextcloud:30-apache"
    restart: "unless-stopped"
    volumes:
      - "nextcloud-app:/var/www/html"
      - "/data/NextcloudData:/var/www/html/data"
  nextcloud-cron:
    container_name: "nextcloud-cron"
    depends_on:
      - "nextcloud-db"
    entrypoint: "/cron.sh"
    environment:
      - "MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=nextcloud-db"
    image: "nextcloud:30-apache"
    restart: "unless-stopped"
    volumes:
      - "nextcloud-app:/var/www/html"
      - "/data/NextcloudData:/var/www/html/data"
  nextcloud-db:
    command: "--transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW"
    container_name: "nextcloud-db"
    environment:
      - "MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=nextcloud-db"
      - "MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}"
    image: "mariadb:10.6"
    restart: "unless-stopped"
    volumes:
      - "nextcloud-db:/var/lib/mysql"
  nginx-proxy:
    container_name: "nginx-proxy"
    environment:
      - "ENABLE_IPV6=true"
    image: "nginxproxy/nginx-proxy"
    networks:
      default: {}
      external:
        gw_priority: 10
        ipv6_address: "2a0e:aa07:e035:d0ce::6666"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - "html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/docker-files/nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:ro"
  onlyoffice:
    container_name: "onlyoffice"
    environment:
      - "VIRTUAL_HOST=onlyoffice.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=onlyoffice.highgarden.blahgeek.com"
      - "JWT_SECRET=${ONLYOFFICE_JWT_SECRET}"
    expose:
      - "80"
    image: "onlyoffice/documentserver"
    restart: "unless-stopped"
  prometheus:
    command: |
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=1y
    container_name: "prometheus"
    environment:
      - "VIRTUAL_HOST=prometheus.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=9090"
      - "LETSENCRYPT_HOST=prometheus.highgarden.blahgeek.com"
    expose:
      - "9090"
    image: "prom/prometheus"
    restart: "unless-stopped"
    volumes:
      - "/var/docker-files/prometheus/:/etc/prometheus/"
      - "prometheus-data:/prometheus"
  prometheus-json-exporter:
    command: "--config.file=/config.yml"
    container_name: "prometheus-json-exporter"
    image: "quay.io/prometheuscommunity/json-exporter"
    restart: "unless-stopped"
    volumes:
      - "/var/docker-files/prometheus-json-exporter/config.yml:/config.yml"
  smokeping:
    container_name: "smokeping"
    environment:
      - "VIRTUAL_HOST=smokeping.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=smokeping.highgarden.blahgeek.com"
    expose:
      - "80"
    image: "linuxserver/smokeping@sha256:d118c7100ded8ccfce7a2c66e0c1f00ce138b3b67eb42ef62e05bc4c57edfff1"
    restart: "unless-stopped"
    volumes:
      - "/var/docker-files/smokeping/data:/data"
      - "/var/docker-files/smokeping/config:/config"
  tailproxy:
    container_name: "tailproxy"
    environment:
      - "VIRTUAL_HOST=tailproxy.highgarden-dyn.blahgeek.com,tailproxy.highgarden-v4.blahgeek.com"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=tailproxy.highgarden-dyn.blahgeek.com,tailproxy.highgarden-v4.blahgeek.com"
      - "STUNNEL_CERT_DIR=/certs/tailproxy.highgarden-dyn.blahgeek.com/"
      - "STUNNEL_LOCAL_PORT=:::8888"
      - "STUNNEL_REMOTE=192.168.0.1:8889"
    expose:
      - "80"
      - "8888"
    image: "blahgeek/tailproxy:0.5"
    networks:
      default: {}
      external:
        gw_priority: 10
        ipv6_address: "2a0e:aa07:e035:d0ce::9607"
    ports:
      - "8888:8888"
    restart: "unless-stopped"
    volumes:
      - "certs:/certs:ro"
  whoami:
    container_name: "whoami"
    environment:
      - "VIRTUAL_HOST=whoami.highgarden.blahgeek.com"
      - "VIRTUAL_PORT=8000"
      - "LETSENCRYPT_HOST=whoami.highgarden.blahgeek.com"
    expose:
      - "8000"
    image: "jwilder/whoami"
    restart: "unless-stopped"
version: "2"
volumes:
  acme: {}
  certs: {}
  grafana-data: {}
  html: {}
  nextcloud-app: {}
  nextcloud-db: {}
  prometheus-data: {}
