version: '2'
name: composes  # backward compatibility

networks:
  external:
    enable_ipv6: true
    ipam:
      config:
        # NOTE: the default docker network (outside of this compose project) uses ...:0001::/80 (in /etc/docker/daemon.json)
        - subnet: 2a0e:aa07:e035:d0ce::/80

# NOTE:
# 1. The default network of this compose project is "default" (actually named "composes_default"),
#    which is ipv4 only and essentially internal (without forwarding)

# 2. For public services,
#    in ipv6 network, only serve in yikai-net (no nat or port expose required, use container's ip directly);
#       (except tailproxy, which is special)
#    in ipv4 network, serve from mudgate (via port forwarding)

volumes:
  nextcloud-app:
  nextcloud-db:
  html:
  certs:
  acme:

services:
  nginx-proxy:
    restart: unless-stopped
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
      - ENABLE_IPV6=true
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker-files/nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
      external:
        ipv6_address: 2a0e:aa07:e035:d0ce::6666

  acme-companion:
    restart: unless-stopped
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=letsencrypt@blahgeek.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    restart: unless-stopped
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.highgarden.blahgeek.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.highgarden.blahgeek.com

  beian-web:
    restart: unless-stopped
    image: blahgeek/beian-web:20251208
    container_name: beian-web
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=blahgeek.com,www.blahgeek.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=blahgeek.com,www.blahgeek.com

  # this is for serving proxy through china-unicom ipv6 address
  # domain is tailproxy.highgarden-dyn.blahgeek.com
  # the domain resolves differently for CN and others (china-unicom and yikai-net, respectively)
  # so that letsencrypt can successfully access it
  tailproxy:
    restart: unless-stopped
    image: blahgeek/tailproxy:0.5
    container_name: tailproxy
    environment:
      - STUNNEL_CERT_DIR=/certs/tailproxy.highgarden-dyn.blahgeek.com/
      # yes.. the below line works. interesting
      - STUNNEL_LOCAL_PORT=2a0e:aa07:e035:d0ce::9607:8888
      - STUNNEL_REMOTE=192.168.0.1:8888
      # virtual_port is actually useless
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=tailproxy.highgarden-dyn.blahgeek.com
      - LETSENCRYPT_HOST=tailproxy.highgarden-dyn.blahgeek.com
    volumes:
      - certs:/certs:ro
    # ipv6 only, no need for port mapping
    expose:
      - "8888"
    networks:
      default:
      external:
        # a special address. iptables would forward CN WAN ipv6 to this addr
        ipv6_address: 2a0e:aa07:e035:d0ce::9607

  # this is for serving proxy through mudgate forward port (ipv4)
  # domain is tailproxy.highgarden-v4.blahgeek.com
  tailproxy-v4:
    restart: unless-stopped
    image: blahgeek/tailproxy:0.5
    container_name: tailproxy-v4
    environment:
      - STUNNEL_CERT_DIR=/certs/tailproxy.highgarden-v4.blahgeek.com/
      - STUNNEL_LOCAL_PORT=8888
      - STUNNEL_REMOTE=192.168.0.1:8888
      # virtual_port is actually useless
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=tailproxy.highgarden-v4.blahgeek.com
      - LETSENCRYPT_HOST=tailproxy.highgarden-v4.blahgeek.com
    volumes:
      - certs:/certs:ro
    expose:
      - "8888"
    ports:
      - "8888:8888"

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    image: nextcloud:30-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    expose:
      - "80"
    networks:
      - default
      # requires "external" network for accessing its own domain (ipv6 only)
      - external
    volumes:
      - nextcloud-app:/var/www/html
      - /data/NextcloudData:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - APACHE_DISABLE_REWRITE_IP=1
      # https://github.com/nextcloud/documentation/pull/11295
      - APACHE_BODY_LIMIT=8589934592
      - TRUSTED_PROXIES=172.16.0.0/12
      - VIRTUAL_HOST=nextcloud.highgarden.blahgeek.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nextcloud.highgarden.blahgeek.com

  nextcloud-cron:
    # same image & volume & mysql environment as above
    image: nextcloud:30-apache
    container_name: nextcloud-cron
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud-app:/var/www/html
      - /data/NextcloudData:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    entrypoint: /cron.sh

  # use onlyoffice now.
  # # the builtin one in nextcloud-app does not contain proper fonts
  # nextcloud-office:
  #   image: collabora/code
  #   container_name: nextcloud-office
  #   restart: unless-stopped
  #   expose:
  #     - "9980"
  #   networks:
  #     - default
  #     # requires "external" network for accessing app domain (ipv6 only)
  #     - external
  #   environment:
  #     - server_name=nextcloud-office.highgarden.blahgeek.com
  #     - extra_params=--o:ssl.enable=false --o:ssl.termination=true
  #     - aliasgroup1=https://nextcloud.highgarden.blahgeek.com:443
  #     - VIRTUAL_HOST=nextcloud-office.highgarden.blahgeek.com
  #     - VIRTUAL_PORT=9980
  #     - LETSENCRYPT_HOST=nextcloud-office.highgarden.blahgeek.com

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: unless-stopped
    networks:
      - default
      # requires "external" network for accessing app domain (ipv6 only)
      - external
    expose:
      - "80"
    environment:
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - VIRTUAL_HOST=onlyoffice.highgarden.blahgeek.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=onlyoffice.highgarden.blahgeek.com

