set dotenv-load  # loading .env file

_list:
  @just --list

render:
    jsonnet -S compose.jsonnet > compose.yml

up: render
    docker --context highgarden compose up -d

down: render
    docker --context highgarden compose down
