- name: Reload BIRDv6 service
  systemd:
    name: bird6
    state: restarted
    daemon-reload: yes

- name: Reload tunnelbroker interfaces
  shell: "/usr/sbin/ifdown {{ item.key }} || true; ip link del {{ item.key }} || true; /usr/sbin/ifup {{ item.key }}"
  with_dict: "{{ tunnelbroker }}"
