- name: Reload BIRDv6 service
  systemd:
    name: bird6
    state: restarted
    daemon-reload: yes


# split down & up, to prevent conflict on routes

- name: Down tunnelbroker interfaces
  shell: "/usr/sbin/ifdown {{ item.key }} || true; ip link del {{ item.key }} || true"
  with_dict: "{{ tunnelbroker }}"

- name: Up tunnelbroker interfaces
  shell: "/usr/sbin/ifup {{ item.key }}"
  with_dict: "{{ tunnelbroker }}"
