- name: Configure tailproxy docker
  tags: tailproxy
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: tailproxy
    image: blahgeek/tailproxy:0.5
    env:
      STUNNEL_CERT_DIR: "/certs/tailproxy.{{ inventory_hostname }}/"
      STUNNEL_LOCAL_PORT: "8888"
      STUNNEL_REMOTE: "100.114.197.1:8888"
      VIRTUAL_PORT: "80"  # actually not used
      VIRTUAL_HOST: "tailproxy.{{ inventory_hostname }}"
      LETSENCRYPT_HOST: "tailproxy.{{ inventory_hostname }}"
    volumes:
      - /var/nginx-proxy/certs:/certs
    ports:
      - "8888:8888/tcp"
    expose:
      - 8888/tcp

- import_tasks: roles/docker/tasks/docker-forward.yml
  tags: tailproxy
  vars:
    ports:
      - 8888
