- import_tasks: roles/docker/tasks/docker-forward.yml
  vars:
    ports:
      - 55555
      - 25
      - 465
      - 587

# port 9099 will be handled separately, see below

- name: Create directories for sync server
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/rslsync
    - /data/Raven
    - /data/Notes

- name: Configure docker rslsync
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: rslsync
    image: resilio/sync:2.7.2
    ports:
      - "9099:8888"
      - "55555:55555"
    volumes:
      - /var/rslsync:/mnt/sync
      - /data/Raven:/mnt/mounted_folders/Raven
      - /data/Notes:/mnt/mounted_folders/Notes
    hostname: "{{ inventory_hostname }}"
    log_driver: json-file
    log_options:
      max-size: "10m"

- name: "Configure iptables port forward for rslsync web"
  iptables_raw:
    name: "docker_forward_rslsync"
    table: nat
    rules: "-A PREROUTING -d 192.168.{{ vpn_subnet_id }}.1 -p tcp --dport 9099 -j DNAT --to 10.255.0.100:9099"

- name: Configure docker webdav
  tags: webdav
  docker_container:
    container_default_behavior: no_defaults
    restart_policy: unless-stopped
    name: webdav
    # maltokyo/docker-nginx-webdav, but patched to add "user root", so no permission issue with rslsync (also root)
    image: blahgeek/nginx-webdav:20240417-patch-root
    volumes:
      - /data/Notes:/media/data/Notes
    env:
      USERNAME: "{{ webdav_username }}"
      PASSWORD: "{{ webdav_password }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "webdav.{{ inventory_hostname }}"
      LETSENCRYPT_HOST: "webdav.{{ inventory_hostname }}"
    expose: 80
