- name: Reload udp2raw server services
  systemd:
    name: "udp2raw@{{ item.key }}-server"
    enabled: yes
    state: restarted
    daemon-reload: yes
  with_dict: "{{ udp2raw }}"

- name: Reload phantun server services
  systemd:
    name: "phantun-server@{{ item.key }}"
    enabled: yes
    state: restarted
    daemon-reload: yes
  with_dict: "{{ phantun }}"

- name: Reload openvpn static server
  systemd:
    name: "openvpn@server"
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload network interfaces
  shell: "ifdown {{ item }} || true; ip link del {{ item }} || true; ifup {{ item }}"
  with_items:
    - unatatp-dummy

- name: Reload unatatp service
  systemd:
    name: unatatp
    enabled: yes
    state: restarted
    daemon-reload: yes
