- name: Reload udp2raw server services
  systemd:
    name: "udp2raw@{{ item.key }}-server"
    enabled: yes
    state: restarted
    daemon-reload: yes
  with_dict: "{{ udp2raw }}"

- name: Reload openvpn static server
  systemd:
    name: "openvpn@server"
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload network interfaces
  shell: "/usr/sbin/ifdown {{ item }} || true; ip link del {{ item }} || true; /usr/sbin/ifup {{ item }}"
  with_items:
    - unatatp-dummy

- name: Reload unatatp service
  systemd:
    name: unatatp
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload kissvpn service
  systemd:
    name: kissvpn-server
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload tayga service
  systemd:
    name: tayga
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload coredns service
  systemd:
    name: coredns
    enabled: yes
    state: restarted
    daemon-reload: yes
