- name: Reload udp2raw server services
  systemd:
    name: "udp2raw@{{ item.key }}-server"
    enabled: yes
    state: restarted
    daemon-reload: yes
  with_dict: "{{ udp2raw }}"

- name: Reload openvpn static server
  systemd:
    name: "openvpn@server"
    enabled: yes
    state: restarted
    daemon-reload: yes

- name: Reload network interfaces
  shell: "ifdown {{ item.name }} || true; ip link del {{ item.name }} || true; ifup {{ item.name }}"
  when: item.when
  with_items:
    - name: tb-ipv6
      when: "{{ tunnelbroker is defined }}"
    - name: unatatp-dummy
      when: yes

- name: Reload unatatp service
  systemd:
    name: "unatatp@{{ unatatp.port }}"
    enabled: yes
    state: restarted
    daemon-reload: yes
