1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "vpn-server.eastwatch.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0:
  type: "PTR"
  value: "wall-tunnel-server.eastwatch.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "vpn-client.eastwatch.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0:
  type: "PTR"
  value: "wall-tunnel-client.eastwatch.blahgeek.com."
6.6.6.6.0.0.0.0.0.0.0.0.0.0.0.0.e.c.0.d:
  type: "PTR"
  value: "web.eastwatch.blahgeek.com."