"":
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"
- type: "MX"
  values:
  - exchange: "aspmx.l.google.com."
    preference: 1
  - exchange: "alt1.aspmx.l.google.com."
    preference: 5
  - exchange: "alt2.aspmx.l.google.com."
    preference: 5
  - exchange: "alt3.aspmx.l.google.com."
    preference: 10
  - exchange: "alt4.aspmx.l.google.com."
    preference: 10
- type: "TXT"
  value: "v=spf1 include:_spf.mx.cloudflare.net include:_spf.google.com ~all"
"*.eastwatch":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.eastwatch.blahgeek.com."
"*.highgarden":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.highgarden.blahgeek.com."
"*.highgarden-dyn":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "blahgeek-highgarden.duckdns.org."
"*.highgarden-dyn-v4":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "blahgeek-highgarden-v4.duckdns.org."
"*.highgarden-dyn-v6":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "blahgeek-highgarden-v6.duckdns.org."
"*.highgarden-v4":
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"
"*.mudgate":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.mudgate.blahgeek.com."
"*.wall":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.wall.blahgeek.com."
_36010C22FBACF112943550BDCDE75424.qnsource.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "51F0713DB016BC7F5E647D460333923C.D9B55B23FD71EC50822B58C4A4D95730.cmcdt3vjd10mbk.trust-provider.com."
_dnsauth.qnsource.hpurl:
  type: "TXT"
  value: "2022070701154107mculg4tn6wkyz7ia7n84wq2xy2wxgnlg1vdzq1ufao3i7qsr"
blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.wall.blahgeek.com."
dnspodcheck:
  type: "TXT"
  value: "70a8f523020ae061e3c2a4142fbbb1e1"
eastwatch:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "149.28.71.244"
google._domainkey:
  type: "TXT"
  value: "v=DKIM1\\; k=rsa\\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmACHFeqUClWjUrUTp7izB56nNy7q9qFtnojQMKQ8MrdqqqBgxWrvJfNWP20DWgMmQ6MXCANRldfJ+zJMEbKoiHsMOVHTb/SApjh3Vj5ONvvcYjAIwPTrFoPu857JI+DHjIVkdP78xHiWB4P7lxFeo7ajt80ov47eKDHiCStfFLnhMfegt0Q2i44WO+kUWG5Dw\" \"qyTb3RORKds94/wjnm5NwLK288ZaGqPq9y9n5ok6ZS46rSRJvm+HjGASNT4BD2+y5XS7sc4xeTpebEnop9MpRtlr1QfNwHltnSjrpV7HCIPten52NsBYhpG7j4v+JsosssYjQ0wtscEkwNRYWaJsQIDAQAB"
highgarden:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "192.168.0.1"
mudgate:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"
qncdn.blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "qncdn.blog.blahgeek.com.qiniudns.com."
qncdn.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "idv0ypk.qiniudns.com."
qndownload.blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "qndownload-blog-blahgeek-com-idvh1ps.qiniudns.com."
qnsource.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "iovip-z0.qbox.me."
wall:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "104.255.70.190"
web.eastwatch:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "149.28.71.244"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a06:a005:08d2:d0ce::6666"
web.highgarden:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a0e:aa07:e035:d0ce::6666"
web.mudgate:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a0e:b107:178f:d0ce::6666"
web.wall:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "104.255.70.190"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a0e:b107:178d:d0ce::6666"
wedding-dev:
  octodns:
    cloudflare:
      proxied: true
  type: "CNAME"
  value: "ffabb251-f5b7-4144-9148-07d032a4160e.cfargotunnel.com."
wedding-photo:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "iovip-z1.qiniuio.com."
www:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "39.98.54.132"