"":
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "47.92.242.60"
- type: "MX"
  values:
  - exchange: "aspmx.l.google.com."
    preference: 1
  - exchange: "alt1.aspmx.l.google.com."
    preference: 5
  - exchange: "alt2.aspmx.l.google.com."
    preference: 5
  - exchange: "alt3.aspmx.l.google.com."
    preference: 10
  - exchange: "alt4.aspmx.l.google.com."
    preference: 10
- type: "TXT"
  value: "v=spf1 include:_spf.mx.cloudflare.net include:_spf.google.com ~all"
"*.eastwatch":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.eastwatch.blahgeek.com."
"*.fleabottom":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.fleabottom.blahgeek.com."
"*.wall":
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.wall.blahgeek.com."
_0d63859ed24b6b968622c24602199b0f.qnsource.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "e6af22ecc0ea81bb019d8a067975242a.f8895168d151b32fa08a12b1fa9bcf12.ttdy86lylw.trust-provider.com."
_4ED1248A677AA6B2156CD55B4257396B.wedding-photo:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "5B04C3679AC589EDA31A120B3004180B.9D31D9F2DA5D402D24BF8784058DCD72.TTDzKipprg.trust-provider.com."
_dnsauth.qnsource.hpurl:
  type: "TXT"
  value: "2022070701154107mculg4tn6wkyz7ia7n84wq2xy2wxgnlg1vdzq1ufao3i7qsr"
blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.wall.blahgeek.com."
eastwatch:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "149.28.71.244"
fleabottom:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "47.92.242.60"
google._domainkey:
  type: "TXT"
  value: "v=DKIM1\\; k=rsa\\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmACHFeqUClWjUrUTp7izB56nNy7q9qFtnojQMKQ8MrdqqqBgxWrvJfNWP20DWgMmQ6MXCANRldfJ+zJMEbKoiHsMOVHTb/SApjh3Vj5ONvvcYjAIwPTrFoPu857JI+DHjIVkdP78xHiWB4P7lxFeo7ajt80ov47eKDHiCStfFLnhMfegt0Q2i44WO+kUWG5Dw\" \"qyTb3RORKds94/wjnm5NwLK288ZaGqPq9y9n5ok6ZS46rSRJvm+HjGASNT4BD2+y5XS7sc4xeTpebEnop9MpRtlr1QfNwHltnSjrpV7HCIPten52NsBYhpG7j4v+JsosssYjQ0wtscEkwNRYWaJsQIDAQAB"
mhome:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "blahgeek-mhome.duckdns.org."
qncdn.blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "qncdn.blog.blahgeek.com.qiniudns.com."
qncdn.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "idv0ypk.qiniudns.com."
qndownload.blog:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "qndownload-blog-blahgeek-com-idvh1ps.qiniudns.com."
qnsource.hpurl:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "iovip-z0.qbox.me."
tg-api.proxy.wall:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "199.180.113.65"
wall:
  octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "199.180.113.65"
web.eastwatch:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "149.28.71.244"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a0e:aa07:e035:d0ce::6666"
web.fleabottom:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "47.92.242.60"
web.wall:
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "199.180.113.65"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a06:a005:08d1:d0ce::6666"
wedding:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "fleabottom.blahgeek.com."
wedding-dev:
  octodns:
    cloudflare:
      proxied: true
  type: "CNAME"
  value: "ffabb251-f5b7-4144-9148-07d032a4160e.cfargotunnel.com."
wedding-photo:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "iovip-z1.qiniuio.com."
www:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "fleabottom.blahgeek.com."
xhome:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "blahgeek-mhome.duckdns.org."