0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "kissvpn-server.dragonstone.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "ovpn-server.dragonstone.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.c.0.d:
  type: "PTR"
  value: "docker-host.dragonstone.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0:
  type: "PTR"
  value: "harrenhal-tunnel-server.dragonstone.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.c.0.d:
  type: "PTR"
  value: "docker-container.dragonstone.blahgeek.com."
1.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "kissvpn-client.dragonstone.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1:
  type: "PTR"
  value: "ovpn-client.dragonstone.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0:
  type: "PTR"
  value: "harrenhal-tunnel-client.dragonstone.blahgeek.com."
6.6.6.6.0.0.0.0.0.0.0.0.0.0.0.0.e.c.0.d:
  type: "PTR"
  value: "web.dragonstone.blahgeek.com."