0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.2:
  type: "PTR"
  value: "kissvpn-server.eastwatch.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.2:
  type: "PTR"
  value: "ovpn-server.eastwatch.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.c.0.d.2:
  type: "PTR"
  value: "docker-host.eastwatch.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.a:
  type: "PTR"
  value: "straywarrior-tunnel-server.eastwatch.blahgeek.com."
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.c.0.d.2:
  type: "PTR"
  value: "docker-container.eastwatch.blahgeek.com."
1.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.2:
  type: "PTR"
  value: "kissvpn-client.eastwatch.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.2:
  type: "PTR"
  value: "ovpn-client.eastwatch.blahgeek.com."
2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.a:
  type: "PTR"
  value: "straywarrior-tunnel-client.eastwatch.blahgeek.com."
6.6.6.6.0.0.0.0.0.0.0.0.0.0.0.0.e.c.0.d.2:
  type: "PTR"
  value: "web.eastwatch.blahgeek.com."
