"":
- octodns:
    cloudflare:
      proxied: false
  type: "A"
  value: "80.251.216.11"
- octodns:
    cloudflare:
      proxied: false
  type: "AAAA"
  value: "2a06:a005:08d1:d0ce::6666"
- type: "MX"
  values:
  - exchange: "aspmx.l.google.com."
    preference: 1
  - exchange: "alt1.aspmx.l.google.com."
    preference: 5
  - exchange: "alt2.aspmx.l.google.com."
    preference: 5
  - exchange: "alt3.aspmx.l.google.com."
    preference: 10
  - exchange: "alt4.aspmx.l.google.com."
    preference: 10
- type: "TXT"
  value: "v=spf1 include:_spf.mx.cloudflare.net include:_spf.google.com ~all"
google._domainkey:
  type: "TXT"
  value: "v=DKIM1\\; k=rsa\\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAPXEssA1Z1Js6uQ7kSGGbNj0N/vER3DygA/GnfIu6oILSUG/5XzSxIZN5t1qkdpwM3vKyMFmYzv0iDszl2PWeP0QDNVOIaMDweUAYZqt3DpoOmFuWNFZOLZs5V63AzpxeUcNQGXzttQFE7p2+TquM/Z3ZzSWggeSx/7MxesWy7taQbyjNuLTqArcAKwEitbqGg31hOJQ+YmByWHPEfPGzPRCIkUZbtSVkTJXefMGR0+252Tmo9KXDuhFnOfLZdPxnn7Tc3NPCbHbcfre2eqquCHWm1m65JEwSDcCxeRqqjgJSyIONxJKKZTY76xt8wNFRq3tMgGACfLfJWAsfWS4QIDAQAB"
raven:
  type: "MX"
  values:
  - exchange: "eastwatch.blahgeek.com."
    preference: 5
  - exchange: "wall.blahgeek.com."
    preference: 10
share:
  octodns:
    cloudflare:
      proxied: false
  type: "CNAME"
  value: "web.wall.blahgeek.com."
