vpn_subnet_id: 43

ipv6_prefix: "{{ yikai_net.eastwatch_prefix }}"

tunnelbroker:
  tb-wall:
    remote: 199.180.113.65  # wall.blahgeek.com
    subnet: "{{ ipv6_prefix | ansible.utils.ipsubnet(64, 1)}}"
    is_server: true
    routes:
      # use two smaller subnets, to avoid conflicts (and set higher priority) than the openvpn route
      - "{{ yikai_net.home_prefix | ansible.utils.ipsubnet(49, 0)}}"
      - "{{ yikai_net.home_prefix | ansible.utils.ipsubnet(49, 1)}}"
      - "{{ yikai_net.wall_prefix }}"
  tb-straywarrior:
    remote: 104.225.147.139
    subnet: "{{ yikai_net.straywarrior_prefix | ansible.utils.ipsubnet(64, 1)}}"
    is_server: true
    routes:
      - "{{ yikai_net.straywarrior_prefix }}"

bgp:
  vultr:
    peer_asn: 64515
    peer_addr: 2001:19f0:ffff::1
    password: legendary
    multihop: 2
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
      - "{{ yikai_net.wall_prefix }}"
      - "{{ yikai_net.straywarrior_prefix }}"
