vpn_subnet_id: 43

ipv6_prefix: "{{ yikai_net.eastwatch_prefix }}"

tunnelbroker:
  tb-wall:
    remote: 67.230.174.235  # wall.blahgeek.com
    subnet: "{{ ipv6_prefix | ansible.netcommon.ipsubnet(64, 1)}}"
    is_server: true
    routes:
      - "{{ yikai_net.home_prefix }}"
      - "{{ yikai_net.wall_prefix }}"

bgp:
  vultr:
    peer_asn: 64515
    peer_addr: 2001:19f0:ffff::1
    password: legendary
    multihop: 2
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
      - "{{ yikai_net.wall_prefix }}"
