vpn_subnet_id: 43

ipv6_prefix: "{{ yikai_net.eastwatch_prefix }}"

bgp:
  vultr:
    peer_asn: 64515
    peer_addr: 2001:19f0:ffff::1
    password: legendary
    multihop: 2
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
      - "{{ yikai_net.wall_prefix }}"
