tunnelbroker_delete:
  - tb-wall

tunnelbroker:
  tb-straywarrior:
    remote: 104.225.147.139
    subnet: "{{ yikai_net.straywarrior_prefix | ansible.utils.ipsubnet(64, 1)}}"
    is_server: true
    routes:
      - "{{ yikai_net.straywarrior_prefix }}"

bgp_advertise_prefixes:
  - "{{ yikai_net.usnet_prefix }}"  # includes my own ipv6_prefix

bgp_connections:
  vultr:
    peer_asn: 64515
    peer_addr: 2001:19f0:ffff::1
    password: legendary
    multihop: 2
    # TODO: no idea why, received routes are all unreachable.
    # so just reject all routes and rely on the default route (system default) for now
    import_filter: |
      reject;
