tunnelbroker_delete:
  - tb-wall

tunnelbroker:
  tb-straywarrior:
    remote: 104.225.147.139
    subnet: "{{ yikai_net.straywarrior_prefix | ansible.utils.ipsubnet(64, 1)}}"
    is_server: true
    routes:
      - "{{ yikai_net.straywarrior_prefix }}"

bgp:
  vultr:
    peer_asn: 64515
    peer_addr: 2001:19f0:ffff::1
    password: legendary
    multihop: 2
    prefixes:
      - "{{ yikai_net.usnet_prefix }}"  # includes my own ipv6_prefix
    export_filter: |
      accept;
