tunnelbroker:
  tb-route64:
    remote: 178.215.228.222
    # my addr: 2a11:6c7:f13:b0::2
    # peer addr: 2a11:6c7:f13:b0::1
    subnet: 2a11:6c7:f13:b0::/126
    routes:
      - 2000::/3
  tb-ifog:
    remote: 193.148.249.30
    # my addr: 2a0c:9a40:a009::2a/126
    subnet: 2a0c:9a40:a009::28/126
    mode: gre
    mtu: 1448
  tb-whitetree:
    remote: "{{ my_hostvars['whitetree.blahgeek.com'].ansible_host }}"
    subnet: "{{ my_hostvars['whitetree.blahgeek.com'].ipv6_prefix | ansible.utils.ipsubnet(64, 2)}}"
    routes:
      - "{{ my_hostvars['whitetree.blahgeek.com'].ipv6_prefix }}"

bgp_advertise_prefixes:
  # NOTE: broadcast both from here and from whitetree
  - "{{ ipv6_prefix }}"
  - "{{ yikai_net.home_prefix }}"

bgp_connections:
  route64:
    peer_asn: 212895
    peer_addr: 2a11:6c7:f13:b0::1
    # already set default router above
    import_filter: |
      reject;
  tb_ifog:
    peer_asn: 209533
    peer_addr: 2a0c:9a40:a009::29
    import_filter: |
      reject;
    # not working... disable export
    export_filter: |
      reject;
