wall_servers:
  - name: hardhome
    host: hardhome.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3001
      route_v4:
        table: 2
        fwmark: '0x2/0xf'
      route_v6:
        table: 2
        fwmark: '0x2/0xf'
  - name: whitetree
    host: whitetree.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3002
      route_v4:
        table: 3
        fwmark: '0x3/0xf'
      route_v6:
        table: 3
        fwmark: '0x3/0xf'

absent_wall_servers:
  - wall
  - ironisland
  - north
  - harrenhal
  - eastwatch
