wall_servers:
  - name: wall
    host: wall.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3000
      route_v4:
        table: 1
        fwmark: '0x1/0xf'
      route_v6:
        table: 1
        fwmark: '0x1/0xf'
  - name: eastwatch
    host: eastwatch.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3001
      route_v4:
        table: 2
        fwmark: '0x2/0xf'
      route_v6:
        table: 2
        fwmark: '0x2/0xf'

absent_wall_servers:
  - ironisland
  - north
  - harrenhal
