# route_v4 and route_v6 have different mechanisms... see mhome's iptable rules.
# for route_v4, the default route is the china net;
# for route_v6, the default route is the yikai net.
wall_servers:
  - name: wall
    host: wall.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3000
      route_v4:
        table: 1
        fwmark: '0x1/0xf'
      route_v6:
        default: true
    kissvpn:
      route_v4:
        table: 2
        fwmark: '0x2/0xf'
      route_v6:
        table: 2
        fwmark: '0x2/0xf'
  - name: eastwatch
    host: eastwatch.blahgeek.com
    openvpn:
      udp2raw:
        client_listen_port: 3001
      # forward:
      #   address: di4gdf-sh-us-fdf66.inkiwike.com
      #   port: 23333
      route_v4:
        table: 3
        fwmark: '0x3/0xf'
      route_v6:
        table: 3
        fwmark: '0x3/0xf'
    kissvpn:
      route_v4:
        table: 4
        fwmark: '0x4/0xf'
      route_v6:
        table: 4
        fwmark: '0x4/0xf'

absent_wall_servers:
  - ironisland
