dns_server: 8.8.8.8

tunnelbroker:
  tb-ifog:
    remote: 193.148.248.18
    # my addr: 2a0c:9a40:a001::e
    subnet: 2a0c:9a40:a001::c/126
    mode: gre
    mtu: 1448
    # routes:
  tb-whitetree:
    remote: "{{ my_hostvars['whitetree.blahgeek.com'].ansible_host }}"
    subnet: "{{ my_hostvars['whitetree.blahgeek.com'].ipv6_prefix | ansible.utils.ipsubnet(64, 1)}}"
    routes:
      - "{{ my_hostvars['whitetree.blahgeek.com'].ipv6_prefix }}"
      - 2000::/3

bgp_advertise_prefixes:
  # NOTE: broadcast both from here and from whitetree
  - "{{ ipv6_prefix }}"
  - "{{ yikai_net.home_prefix }}"

bgp_connections:
  tb_ifog:
    peer_asn: 209533
    peer_addr: 2a0c:9a40:a001::d
    # export_filter: |
    #   bgp_path.prepend({{ my_asn }});
    #   bgp_path.prepend({{ my_asn }});
    #   bgp_path.prepend({{ my_asn }});
    #   accept;
    # 不知道为什么，prepend三次之后流量还是会从这里来（比较便宜？）
    # 质量不太行，还是关掉吧
    export_filter: |
      reject;
    # no import for this connection, use default routes above
    import_filter: |
      reject;
