tunnelbroker:
  tb-ifog:
    remote: 193.148.248.18
    # my addr: 2a0c:9a40:a001::e
    subnet: 2a0c:9a40:a001::c/126
    mode: gre
    mtu: 1448
    routes:
      - 2000::/3

bgp:
  tb_ifog:
    peer_asn: 209533
    peer_addr: 2a0c:9a40:a001::d
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
    export_filter: |
      accept;
