tunnelbroker:
  tb-wall:
    remote: "{{ my_hostvars['wall.blahgeek.com'].ansible_host }}"
    is_server: true
    subnet: "{{ ipv6_prefix | ansible.utils.ipsubnet(64, 1) }}"
    routes:
      - "{{ yikai_net.home_prefix }}"
      - "{{ my_hostvars['wall.blahgeek.com'].ipv6_prefix }}"

bgp_advertise_prefixes:
  - "{{ ipv6_prefix }}"
  # - "{{ yikai_net.home_prefix }}"
  # - "{{ my_hostvars['wall.blahgeek.com'].ipv6_prefix }}"

bgp_connections:
  tb_ifog:
    peer_asn: 34927
    peer_addr: 2a0c:9a40:2711:111::1
    export_filter: |
      bgp_path.prepend({{ my_asn }});
      accept;

  fogixp:
    peer_asn: 47498
    peer_addr: 2001:7f8:ca:1::111
    export_filter: |
      bgp_path.prepend({{ my_asn }});
      accept;
