- assert:
    that: ansible_os_family == 'Debian'

- name: Configure iptables for nat masquerade
  iptables_raw:
    name: nat_masquerade
    table: nat
    rules: |
      -A POSTROUTING -s 192.168.0.0/16 -j MASQUERADE
      -A POSTROUTING -s 100.64.0.0/10 -j MASQUERADE

- name: Remove legacy unatatp system service
  systemd:
    name: "unatatp@{{ unatatp.port }}"
    enabled: no
    state: stopped
  ignore_errors: yes
  tags:
    - unatatp

- name: Remove legacy unatatp systemd service config
  file:
    path: /etc/systemd/system/unatatp@.service
    state: absent
  tags:
    - unatatp

- name: Download and install unatatp
  when: unatatp is defined
  get_url:
    url: https://github.com/blahgeek/unatatp/releases/download/0.3/unatatp
    checksum: sha1:9de21944d7462a942174e4bdb152ca7509fc8701
    dest: /usr/local/bin/unatatp
    mode: 0755
  notify:
    - Reload unatatp service
  tags:
    - unatatp

- name: Add unatatp systemd service
  when: unatatp is defined
  template:
    src: systemd/unatatp.service.j2
    dest: /etc/systemd/system/unatatp.service
  vars:
    unatatp_binary_path: /usr/local/bin/unatatp
  notify:
    - Reload unatatp service
  tags:
    - unatatp

- name: Configure unatatp policy routing
  when: unatatp is defined
  template:
    src: network/unatatp-dummy.j2
    dest: /etc/network/interfaces.d/unatatp-dummy
  notify: Reload network interfaces
  tags:
    - unatatp

- name: Configure iptables for unatatp
  when: unatatp is defined
  iptables_raw:
    name: unatatp_route
    table: mangle
    rules: |
      -A PREROUTING -m addrtype --dst-type local -j ACCEPT
      -A PREROUTING -s 192.168.0.0/16 ! -d 192.168.0.0/16 -p tcp -j TPROXY --on-port {{ unatatp.port }} --on-ip 127.0.0.1 --tproxy-mark {{ unatatp.route_fwmark }}
      -A PREROUTING -m socket --transparent -j MARK --set-xmark {{ unatatp.route_fwmark }}
  tags:
    - unatatp

- name: Configure ip6tables for unatatp
  when: unatatp is defined and ipv6_prefix is defined
  iptables_raw:
    ipversion: 6
    name: unatatp_route_6
    table: mangle
    # NOTE: only handle {home_prefix(/48)}:dea0::/64. allow incoming tcp connections for others. see home rules.v6
    rules: |
      -A PREROUTING -m addrtype --dst-type local -j ACCEPT
      -A PREROUTING -s {{ yikai_net.home_prefix | ansible.utils.ipsubnet(60, 0xdea) }} -p tcp -j TPROXY --on-port {{ unatatp.port }} --on-ip ::1 --tproxy-mark {{ unatatp.route_fwmark }}
  tags:
    - unatatp

- import_tasks: roles/common-wall/tasks/install-udp2raw.yml
  notify: Reload udp2raw server services

- name: Stop old udp2raw server services
  systemd:
    name: "udp2raw@{{ item }}"
    enabled: false
    state: stopped
  with_items: "{{ udp2raw_cleanup_configs }}"

- name: Cleanup old udp2raw configs
  file:
    path: "/etc/udp2raw/{{ item }}.conf"
    state: absent
  with_items: "{{ udp2raw_cleanup_configs }}"

- name: Install udp2raw server configs
  template:
    src: udp2raw.conf.j2
    dest: "/etc/udp2raw/{{ item.key }}-server.conf"
  with_dict: "{{ udp2raw }}"
  notify: Reload udp2raw server services

- name: Configure iptables for udp2raw
  iptables_raw:
    name: "udp2raw_filter_{{ item.key }}"
    table: filter
    rules: "-A INPUT -p tcp -m tcp --dport {{ item.value.server_listen_port }} -j DROP"
  with_dict: "{{ udp2raw }}"

- import_tasks: roles/common-wall/tasks/install-openvpn.yml
  notify: Reload openvpn static server
  tags:
    - vpn

- name: Configure openvpn static server
  template:
    src: openvpn/static-server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: Reload openvpn static server
  tags:
    - vpn


- name: Remove old iptable rules
  iptables_raw:
    name: "{{ item }}"
    state: absent
  with_items:
    - udp2raw_filter
    - phantun_nat_openvpn
  tags:
    - vpn

- name: Stop old server services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - phantun-server@openvpn
  ignore_errors: true
  tags:
    - vpn


- import_tasks: roles/common-wall/tasks/install-kissvpn.yml
  notify: Reload kissvpn service
  tags:
    - vpn

- name: Copy kissvpn server up script
  template:
    src: kissvpn/server.up.sh.j2
    dest: /etc/kissvpn/server.up.sh
    mode: 0755
  notify: Reload kissvpn service
  tags:
    - vpn
