- name: Install udp2raw client configs for openvpn
  template:
    src: udp2raw-for-openvpn.conf.j2
    dest: "/etc/udp2raw/{{ item.name }}.conf"
  notify: Reload udp2raw client services for openvpn
  when: item.openvpn.udp2raw is defined
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client

- name: Install openvpn client up scripts
  template:
    src: openvpn/client-up.sh.j2
    dest: "/etc/openvpn/client/{{ item.name }}-up.sh"
    mode: 0755
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client

- name: Install openvpn client down scripts
  template:
    src: openvpn/client-down.sh.j2
    dest: "/etc/openvpn/client/{{ item.name }}-down.sh"
    mode: 0755
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client

- name: Install openvpn client configs
  template:
    src: openvpn/client.conf.j2
    dest: "/etc/openvpn/client/{{ item.name }}.conf"
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
