- name: Remove old udp2raw services for openvpn
  systemd:
    name: "udp2raw@{{ item }}"
    enabled: no
    state: stopped
  ignore_errors: yes
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Remove old udp2raw client configs for openvpn
  file:
    path: "/etc/udp2raw/{{ item }}.conf"
    state: absent
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- import_tasks: roles/common-wall/tasks/install-udp2raw.yml
  notify: Reload udp2raw client services for openvpn
  tags:
    - wall-client

- name: Install udp2raw client configs for openvpn
  template:
    src: udp2raw-for-openvpn.conf.j2
    dest: "/etc/udp2raw/{{ item.name }}.conf"
  notify: Reload udp2raw client services for openvpn
  when: item.openvpn.udp2raw is defined
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- import_tasks: roles/common-wall/tasks/install-openvpn.yml
  notify: Reload openvpn client services
  tags:
    - wall-client

- name: Install openvpn client up scripts
  template:
    src: openvpn/client-up.sh.j2
    dest: "/etc/openvpn/client/{{ item.name }}-up.sh"
    mode: 0755
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Install openvpn client down scripts
  template:
    src: openvpn/client-down.sh.j2
    dest: "/etc/openvpn/client/{{ item.name }}-down.sh"
    mode: 0755
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Remove old openvpn services
  systemd:
    name: "openvpn-client@{{ item }}"
    enabled: no
    state: stopped
  ignore_errors: yes
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Remove old openvpn client up scripts
  file:
    path: "/etc/openvpn/client/{{ item }}-up.sh"
    state: absent
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Remove old openvpn client down scripts
  file:
    path: "/etc/openvpn/client/{{ item }}-down.sh"
    state: absent
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Install openvpn client configs
  template:
    src: openvpn/client.conf.j2
    dest: "/etc/openvpn/client/{{ item.name }}.conf"
  notify: Reload openvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Remove old openvpn client configs
  file:
    path: "/etc/openvpn/client/{{ item }}.conf"
    state: absent
  with_items: "{{ absent_wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- import_tasks: roles/common-wall/tasks/install-kissvpn.yml
  notify: Reload kissvpn client services
  tags:
    - wall-client

- name: Copy kissvpn client configs
  when: item.kissvpn is defined
  template:
    src: kissvpn/client.conf.j2
    dest: /etc/kissvpn/{{ item.name }}.conf
    mode: 0755
  notify: Reload kissvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config

- name: Copy kissvpn client up scripts
  when: item.kissvpn is defined
  template:
    src: kissvpn/client.up.sh.j2
    dest: /etc/kissvpn/{{ item.name }}.up.sh
    mode: 0755
  notify: Reload kissvpn client services
  with_items: "{{ wall_servers }}"
  tags:
    - wall-client
    - wall-client-config
