- name: Install wireguard
  package:
    name:
      - wireguard
      - wireguard-tools
    state: present
  tags:
    - wireguard

- name: Ensure dir /etc/wireguard
  file:
    path: /etc/wireguard/
    state: directory
    mode: 0755
  tags:
    - wireguard

- name: Add wireguard config
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
  notify:
    - Reload wireguard
  tags:
    - wireguard
