- name: Install wireguard
  package:
    name:
      - wireguard
      - wireguard-tools
    state: present
  tags:
    - wireguard

- name: Ensure dir /etc/wireguard
  file:
    path: /etc/wireguard/
    state: directory
    mode: 0755
  tags:
    - wireguard

- name: Add wireguard config
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
  notify:
    - Reload wireguard
  tags:
    - wireguard

- name: Configure iptables to forward port to highgarden
  when: wireguard_hosts[inventory_hostname].is_server is defined and wireguard_hosts[inventory_hostname].is_server
  iptables_raw:
    name: wireguard_forward
    # 172.16.x.x is nat64 address, see tayga.conf
    # port 3000 is for newhome-bridge. remove after 2025 May
    table: nat
    rules: |
      -A PREROUTING ! -i wg* -p tcp --dport 443 -j DNAT --to-destination 172.16.1.1
      -A PREROUTING ! -i wg* -p tcp --dport 80 -j DNAT --to-destination 172.16.1.1
      -A PREROUTING ! -i wg* -p tcp --dport 8888 -j DNAT --to-destination 172.16.1.2
      -A PREROUTING ! -i wg* -p udp --dport 3000 -j DNAT --to-destination 192.168.0.178
  tags:
    - wireguard
    - wireguard-iptables

