openvpn:
  server_listen_port: 3000

udp2raw:
  openvpn:
    server_listen_port: 8443
    server_local_port: 3000  # same as openvpn.server_listen_port
    raw_mode: faketcp
    cipher_mode: none
    key: blahnet

yikai_net:
  # 2a06:a005:08d0::/44 is from route48.org, but I'm no longer its maintainer
  # only the "/44" has corresponding "route" object and I cannot further add "/48"s.
  # so to make sure it works, I should always broadcast "/44" in bgp.
  usnet_prefix: 2a06:a005:08d0::/44
  # so the following sites will always belong to usnet
  eastwatch_prefix: 2a06:a005:08d2::/48
  straywarrior_prefix: 2a06:a005:08da::/48

  # this is the orignal prefix assigned from ASN sponsor. use it for home
  home_prefix: 2a0e:aa07:e035::/48

  # 2a0e:b107:178c::/46 is from tunnelbroker.ch
  north_prefix: 2a0e:b107:178c::/48
  wall_prefix: 2a0e:b107:178d::/48

ipv6_vpn_subnet_id: 0x1000
