openvpn:
  server_listen_port: 3000

udp2raw:
  openvpn:
    server_listen_port: 8443
    server_local_port: 3000  # same as openvpn.server_listen_port
    raw_mode: faketcp
    cipher_mode: none
    key: blahnet

yikai_net:
  usnet_prefix: 2a06:a005:08d0::/44
  home_prefix: 2a06:a005:08d0::/48
  wall_prefix: 2a06:a005:08d1::/48
  eastwatch_prefix: 2a0e:aa07:e035::/48
  north_prefix: 2a0e:b107:178c::/48
  straywarrior_prefix: 2a06:a005:08da::/48

ipv6_vpn_subnet_id: 0x1000
