openvpn:
  server_listen_port: 3000

udp2raw:
  openvpn:
    server_listen_port: 8443
    server_local_port: 3000  # same as openvpn.server_listen_port
    raw_mode: faketcp
    cipher_mode: none
    key: blahnet

unatatp:
  port: 9999
  route_table: 100
  route_fwmark: "0x100/0xf00"
  ipv6_subnet_id: 0x3000

ipv6_vpn_subnet_id: 0x1000
